# Generated by Django 4.1.2 on 2022-10-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_rename_subtitle_flexpage_texte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexpage',
            old_name='texte',
            new_name='text',
        ),
    ]
