# Generated by Django 4.1.2 on 2022-10-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_rename_texte_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Neque neque quaerat non sit amet. Porro labore eius voluptatem. Tempora adipisci neque porro velit ipsum velit dolor. Sit adipisci voluptatem porro magnam velit. Ut aliquam ipsum quiquia. Porro eius porro adipisci. Ipsum sit ut amet aliquam est. Quaerat non ipsum aliquam est tempora porro labore.', max_length=500, null=True),
        ),
    ]
