# Generated by Django 4.1.2 on 2022-10-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Labore sit est quaerat velit velit est. Ut ut quaerat consectetur quisquam magnam. Sit consectetur quiquia velit consectetur sit adipisci porro. Ipsum labore sit eius quisquam. Dolorem amet dolore dolorem dolore tempora quaerat quisquam. Ipsum dolorem quisquam labore. Dolorem quaerat etincidunt labore. Etincidunt voluptatem quaerat sit consectetur neque. Numquam quaerat sit etincidunt. Etincidunt non ut quaerat dolore sit numquam.', max_length=500, null=True),
        ),
    ]
