# Generated by Django 4.1.2 on 2022-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Labore est modi numquam aliquam. Amet est neque ut est. Numquam quisquam amet aliquam sed aliquam labore. Quaerat numquam etincidunt porro. Dolor aliquam dolor ut amet. Magnam numquam numquam velit ipsum. Quaerat velit tempora magnam dolorem dolorem.', max_length=500, null=True),
        ),
    ]
