# Generated by Django 4.1.2 on 2022-10-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0009_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Est tempora eius dolorem. Aliquam quisquam est dolore velit dolorem quiquia velit. Quiquia quiquia consectetur ut numquam. Aliquam voluptatem dolore quisquam porro aliquam dolorem quisquam. Dolor sed consectetur quaerat adipisci. Voluptatem magnam dolorem sed. Voluptatem eius etincidunt tempora ut magnam etincidunt sed. Porro est neque quaerat.', max_length=500, null=True),
        ),
    ]
