# Generated by Django 4.1.2 on 2022-10-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0010_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Sit ipsum dolore sit etincidunt labore dolorem. Neque adipisci etincidunt labore non dolore. Dolore neque magnam adipisci quisquam neque est. Dolorem amet consectetur porro quisquam. Amet dolor velit tempora.', max_length=500, null=True),
        ),
    ]
