# Generated by Django 4.1.2 on 2022-10-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0011_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Non amet magnam porro sit quaerat aliquam modi. Quaerat adipisci adipisci consectetur tempora magnam porro. Dolore eius quisquam quisquam etincidunt sit. Est dolore quiquia modi labore porro. Ipsum aliquam quisquam sed dolor ipsum porro dolorem.', max_length=500, null=True),
        ),
    ]
