# Generated by Django 4.1.2 on 2022-10-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0012_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Velit dolore magnam neque. Magnam ipsum porro aliquam dolorem modi est quiquia. Velit aliquam quisquam quiquia eius ut voluptatem. Est non modi ut etincidunt. Magnam dolore amet neque. Etincidunt voluptatem numquam sit non sed ipsum. Porro voluptatem quiquia ut quaerat. Numquam adipisci aliquam velit amet. Numquam tempora etincidunt quisquam dolor.', max_length=500, null=True),
        ),
    ]
