# Generated by Django 4.1.2 on 2022-10-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0013_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Voluptatem modi amet tempora quaerat ut neque non. Adipisci adipisci dolorem dolor. Numquam numquam dolorem porro. Dolor quaerat ipsum sit modi. Sit sit tempora neque dolor. Porro sed quiquia modi dolorem numquam magnam. Dolor aliquam voluptatem aliquam neque voluptatem non labore. Consectetur quaerat amet velit. Labore quaerat consectetur neque.', max_length=500, null=True),
        ),
    ]
