# Generated by Django 4.1.2 on 2022-10-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0014_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Velit labore amet porro modi. Numquam dolor dolor porro. Ipsum velit dolore non ut dolor dolor. Quiquia consectetur quaerat numquam sit voluptatem eius modi. Velit sed modi etincidunt quiquia. Aliquam aliquam sed sed quisquam sit ut tempora. Porro est est quaerat sed etincidunt eius. Amet sit amet aliquam quisquam tempora quaerat sed.', max_length=500, null=True),
        ),
    ]
