# Generated by Django 4.1.2 on 2022-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0015_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Aliquam non non adipisci ipsum tempora dolore quisquam. Dolorem voluptatem labore eius. Consectetur quiquia eius ipsum ut eius sed. Consectetur tempora aliquam dolore aliquam dolorem ut dolorem. Voluptatem sed labore quaerat dolor consectetur. Quiquia voluptatem voluptatem amet sit. Sed quisquam voluptatem amet.', max_length=500, null=True),
        ),
    ]
