# Generated by Django 4.1.2 on 2022-10-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0016_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Sed neque est non sed. Sed adipisci est consectetur magnam. Sed est etincidunt dolore quiquia consectetur est tempora. Labore velit consectetur magnam consectetur etincidunt. Aliquam ipsum ipsum magnam ut numquam porro. Adipisci non dolorem sed ipsum quaerat. Neque dolor consectetur dolorem ipsum. Quaerat voluptatem voluptatem porro quiquia. Consectetur consectetur quiquia quisquam velit modi tempora. Dolor quaerat numquam eius amet est porro etincidunt.', max_length=500, null=True),
        ),
    ]
