# Generated by Django 4.1.2 on 2022-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0017_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Neque est est sit amet. Eius eius dolore modi quiquia. Non ipsum amet non non etincidunt porro. Eius consectetur sed modi aliquam magnam ipsum. Aliquam tempora tempora dolor porro labore. Neque quaerat non non dolor labore ut. Magnam modi labore quaerat. Magnam ipsum dolore porro modi est sit quisquam. Velit adipisci tempora consectetur neque non numquam magnam. Quisquam quiquia numquam neque.', max_length=500, null=True),
        ),
    ]
