# Generated by Django 4.1.2 on 2022-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0018_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Est sed labore eius quisquam velit sit amet. Neque neque etincidunt dolorem ipsum porro porro voluptatem. Quisquam dolorem numquam porro sed etincidunt labore. Aliquam quaerat ut modi. Tempora ipsum adipisci ipsum consectetur sed porro. Quiquia ut quisquam porro etincidunt etincidunt consectetur. Amet dolore voluptatem aliquam est. Sit neque dolor sit voluptatem consectetur voluptatem.', max_length=500, null=True),
        ),
    ]
