# Generated by Django 4.1.2 on 2022-10-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0019_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Voluptatem tempora neque ipsum consectetur ipsum magnam dolor. Labore velit ut modi consectetur quiquia dolor. Non eius sit eius. Quisquam eius numquam dolor ipsum dolor consectetur. Neque consectetur magnam porro quaerat. Consectetur consectetur quisquam quisquam velit.', max_length=500, null=True),
        ),
    ]
