# Generated by Django 4.1.2 on 2022-10-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0020_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Dolor quaerat modi dolor dolore. Voluptatem quisquam est magnam porro ut est tempora. Est voluptatem modi quisquam quaerat consectetur. Labore est non ipsum. Ut voluptatem ut magnam neque dolore eius sit. Quisquam quisquam ut aliquam quaerat dolor neque. Dolor modi dolore labore quaerat amet aliquam velit. Quaerat aliquam labore ut eius velit. Aliquam adipisci dolor numquam numquam sit.', max_length=500, null=True),
        ),
    ]
