# Generated by Django 4.1.2 on 2022-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0021_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Aliquam numquam magnam porro dolore numquam porro. Numquam numquam ipsum etincidunt consectetur quiquia. Est neque magnam tempora dolore. Etincidunt magnam etincidunt dolorem neque. Est tempora voluptatem voluptatem aliquam non consectetur eius. Modi etincidunt quaerat sed sit.', max_length=500, null=True),
        ),
    ]
